name: Diceware CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:


permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            build
            kover
            --info

      - name: Extract and print coverage
        run: |
          sudo apt-get update && sudo apt-get install libxml2-utils
          covered=$(xmllint --xpath 'string(/report/counter[@type="LINE"]/@covered)' web/build/reports/kover/report.xml)
          missed=$(xmllint --xpath 'string(/report/counter[@type="LINE"]/@missed)' web/build/reports/kover/report.xml)
          total=$(awk "BEGIN { print 100.0*$covered/($covered+$missed) }")
          echo "Total line coverage: $total%"
          echo "covered=$covered" >> $GITHUB_OUTPUT
          echo "missed=$missed" >> $GITHUB_OUTPUT
          echo "coverage_pct=$total" >> $GITHUB_OUTPUT
          
          echo "### Line coverage" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
          echo "- Covered: $covered" >> $GITHUB_STEP_SUMMARY
          echo "- Missed: $missed" >> $GITHUB_STEP_SUMMARY
          echo "- Coverage: $total" >> $GITHUB_STEP_SUMMARY

      - name: Upload build reports
        uses: actions/upload-artifact@v3
        with:
          name: build-reports
          path: |
            core/build/reports/
            web/build/reports/
